Exam
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #14
Opened 2024-12-23 18:29 UTC by Fellis-a

# Экзамен

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

- [х ] В корневой папке репозитория создать базовое приложение exam с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
- [х]  Сверстать 2 страницы и необходимые компоненты
- [ х]  Использовать стили. Дизайн должен быть похожим на макет
- [ х]  Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- [ ]  Реализовать перевод с неизвестного языка (автоопределитель из API)
- [ х]  Сохранять историю переводов в localStorage
- [ х]  Использовать zustand
- [ x]  Использовать React-router для перехода между страницами
- [ ]  Задеплоить решение, используя GitHub Actions
- [ ]  Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-23 21:11 UTC, Fellis-a commented
Решила сделать в стиле чата
[https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/](https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/)

2024-12-28 00:20 UTC, HaseProgram requested changes
Привет, работа хорошая, код на хорошем уровне, особо придраться не к чему)

Но есть к чему придраться на уровне верстки)
<img width="906" alt="image" src="https://github.com/user-attachments/assets/575b3113-8499-4692-906c-bec94b68d631" />
<img width="906" alt="image" src="https://github.com/user-attachments/assets/44e3d245-5724-4767-9987-6d642e9ade9b" />

Хочется чуть более аккуратного. Можно сделать в стиле чата, но чуть более рабочий вариант (белый текст в белой форме вообще выглядит как нерабочее приложение :))

Готов сейчас поставить 36 баллов из 46
10 доп баллов поставлю за
- [ ] Починить верстку
- [ ] Добавить языки из [файла с языками](https://github.com/education-vk-company/vk-edu-fullstack/blob/master/vk-edu-2024/front/exam/languages.json)
- [ ] Сделать не только автоопределение языка, но и выбор

2024-12-28 00:20 UTC, HaseProgram commented on exam/src/pages/Home/index.tsx
> +            setTranslatedText(result);
В целом, в таком подходе можно было бы использовать сразу значение из стора (последний элемент массива) и не заводить отдельный стейт

2024-12-28 00:20 UTC, HaseProgram commented on exam/src/pages/Home/index.tsx
> +                        <option value="auto">Auto</option>
Файлик с языками тут бы зашел получше, конечно :)

2025-01-06 17:54 UTC, Fellis-a commented
Привет! Все исправила. К сожалению, я не учла, что цветовая тема шаблона автоматически адаптируется под системную тему интерфейса компьютера. Так как у меня была установлена темная тема, верстка оказалась оптимизированной только для нее, а для светлой темы выглядела некорректно 😅
Учту этот момент и впредь буду внимательнее. 
Спасибо за замечания! 🤓

2025-01-12 18:41 UTC, HaseProgram approved these changes
Теперь совсем классно, 46 ставлю 🎉

2025-01-12 18:41 UTC, merged