ДЗ 2
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #2
Opened 2024-09-26 11:07 UTC by Fellis-a

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

[https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/](https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/)

Что было сделано:
* Стилизация в соответствии с макетом (с использованием CSS Flexbox).
* Сохранение сообщений в localstorage. Выгрузка сообщений из localstorage при обновлении страницы. 
* Настроен деплой на GitHub pages.

2024-09-28 17:41 UTC, sh4rkizz requested changes
Рекомендации закинул в лс

2024-09-29 09:58 UTC, Fellis-a commented
![Снимок экрана 2024-09-28 в 13 48 05](https://github.com/user-attachments/assets/a0da9444-1b16-4e1d-83ca-08d7e3f9d1b6)

2024-09-29 14:10 UTC, Fellis-a commented
<img width="315" alt="Снимок экрана 2024-09-29 в 17 09 52" src="https://github.com/user-attachments/assets/885da061-c2b0-4734-923c-db44026eaa84">

2024-09-29 14:15 UTC, sh4rkizz approved these changes
lgtm, сделала конфетку

2024-10-01 21:39 UTC, HaseProgram approved these changes
Супер! 12!

2024-10-01 21:39 UTC, merged