ДЗ 3
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #3
Opened 2024-10-06 23:28 UTC by Fellis-a

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Добавлена возможность перехода от конкретного чата к общему списку чатов и наоборот.
* Код нового задания разбит на отдельные файлы. 
* Использованы новые возможности JavaScript

2024-10-07 13:20 UTC, sh4rkizz requested changes
Хочу похвалить твою организацию кода, потребовались минимальные доработки чтобы перейти от 2-ой домашки к 3-ей, а также качественную настройку webpack.js

Давай поправим замечания, чтобы было проще работать в дальнейшем)

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/css/addChat.css
> +    background-color: var(--color-);
Похоже на забытый цвет, ниже есть определение определение этого свойства, это можно спилить

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/chats.html
> +                    <p class="chat__last-message">Все хорошо</p>
Хорошо когда все хорошо, но предлагаю брать сообщения для этой страницы из storage
[учти, буду ломать некорректными вводами]

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/chats.html
> +    <button class="floating-button" id="createChatButton"><i class="material-icons">edit</i></button>
Давай накинем обработчиков событий на эту кнопку

Можешь попробовать воспользоваться GET-параметрами [например ?chat_id=<ID>], а при открытии чата смотреть в localStorage, есть ли там чат с таким ID

Создание чата кнопкой в таком случае у тебя создает новую запись в localStorage о неком chat_id [который в этом случае нужно генерировать рандомно]

Предлагаю также указывать имя собеседника в модалке - mvp сделаем prompt

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/index.js
> +
Давай воспользуемся тегом \<a>, а этот обработчик спилим, чтобы верстка соответствовала логическим элементам

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/js/chats.js
> +});
Аналогично можно сделать чатики ссылками, чтобы не манипулировать .href

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/webpack.config.js
> +        }),
Классная настройка webpack, молодец

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/chats.html
> +                alt="Avatar">
Потенциально, аватарку тоже можно класть в storage, чтобы на странице чатика она появлялась именно оттуда [благо 5 МБ доступной памяти сделать такое позволяет для большого количества чатиков]

Сейчас немного ломается мозг, когда переходишь к ивану, а получаешь шрека Алисы

2024-10-07 13:20 UTC, sh4rkizz commented on simple-chat/src/index.js
> +    }
getMessages()[selectedChatId] || [];

2024-10-10 13:54 UTC, sh4rkizz approved these changes
атлишна! lgtm

2024-10-10 14:06 UTC, Fellis-a commented
![Снимок экрана 2024-10-10 в 17 06 15](https://github.com/user-attachments/assets/44cd269f-55ab-497b-a708-47865fe0e19d)

2024-10-11 15:01 UTC, martinkomitsky approved these changes
Ну что за анаконда!

2024-10-11 15:02 UTC, martinkomitsky commented
12!

2024-10-11 15:02 UTC, merged