ДЗ 5
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #5
Opened 2024-10-23 21:00 UTC by Fellis-a

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Компоненты переписаны на react. 
* Восстановлены стили и функциональность.
* Восстановлены переходы.

2024-10-24 10:40 UTC, sh4rkizz requested changes
чинить будем!

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +import { useContext } from 'react';
Предлагаю такие штуки называть index.jsx 
[
 . одноименные с директорией лежать не должны 
 .   \+ явно указывает откуда, что импортируется
 .   \+ импорт на один "/<...>/" меньше содержит
]

<img width="339" alt="изображение" src="https://github.com/user-attachments/assets/38d7c5da-2040-485c-9acb-4157e7597df3">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/components/FloatingButton/FloatingButton.jsx
> +                            onChange={(e) => setChatName(e.target.value)}
Можно без перерендеров обрабатывать input-ы
[с использованием useRef]

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
какой-то странный отступ от хедера

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/d79a4f1b-316a-4b88-89f3-5ec43a792a65">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
давай title поменяем и какую-нибудь красивую картинку воткнем

<img width="111" alt="изображение" src="https://github.com/user-attachments/assets/dad840b1-4ff0-404b-9523-cc0a424a35d2">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
пупупу в хедере при длинном тексте
<img width="342" alt="изображение" src="https://github.com/user-attachments/assets/d11a652b-b9b6-47f3-b5df-53bb047e6e9e">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
Давай эту штуку как-нибудь красивенько в центр контентной области положим

<img width="926" alt="изображение" src="https://github.com/user-attachments/assets/b63fdadb-17dc-4972-be4d-5de94e80cbd1">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
формочка на Enter не отправляется :с
<img width="926" alt="изображение" src="https://github.com/user-attachments/assets/a9d83c80-cfb3-4120-bbf6-2f1e3ae8340d">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
Более правильным UX будет стирание этого текста при закрытии модалки [или сброс при открытии]
Также предлагаю запретить скролл страницы когда эта модалка открыта

<img width="437" alt="изображение" src="https://github.com/user-attachments/assets/6da90eb3-3529-484b-b9d1-ef80af4b8874">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          <Header title="Чаты" />
понимаю что элемент некликабельный, но давай все же дадим ему /<button>
предлагаю с padding: 8px;, чтобы мобилке было удобно

<img width="485" alt="изображение" src="https://github.com/user-attachments/assets/55e4ffec-80ac-45a9-94f9-535a375f6b3b">

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/main.jsx
> +import { StrictMode } from 'react'
давай файл тоже index.jsx назовем)

2024-10-24 10:40 UTC, sh4rkizz commented on react-chat/src/components/ChatList/ChatList.jsx
> +export default ChatList;
Если получится, хотелось бы увидеть это)

<img width="470" alt="изображение" src="https://github.com/user-attachments/assets/66ff8e28-f3ae-4b9d-b5df-f318e235ab8f">

2024-10-25 19:53 UTC, sh4rkizz approved these changes
lgtm, как всегда на высшем уровне!

2024-10-27 17:50 UTC, martinkomitsky commented
12! :фире еможи:

2024-10-27 17:50 UTC, merged