Подключен react-router и добавлена страница профиля
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #6
Opened 2024-10-31 13:30 UTC by Fellis-a

# Домашнее задание № 6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/
<img width="309" alt="Снимок экрана 2024-10-31 в 16 29 17" src="https://github.com/user-attachments/assets/1c84059a-91b7-4bb1-9fcc-bbb54a237337">
<img width="306" alt="Снимок экрана 2024-10-31 в 16 29 36" src="https://github.com/user-attachments/assets/a5619953-8bcc-4e3b-8058-4d1cf4a7d69c">

Что было сделано:
* Подключен react-router, настроена маршрутизация
* Создана страница профиля
* Добавлено бургер-меню для перехода к странице профиля

2024-10-31 13:31 UTC, Fellis-a commented
<img width="309" alt="Снимок экрана 2024-10-31 в 16 29 17" src="https://github.com/user-attachments/assets/ccd67afb-036c-413b-96fe-465d86f89dbf">
<img width="306" alt="Снимок экрана 2024-10-31 в 16 29 36" src="https://github.com/user-attachments/assets/49b34fd6-b5b6-449e-a24e-ecb012d92419">

2024-10-31 21:00 UTC, sh4rkizz requested changes
в целом очень хорошо, но заметил много шероховатостей, которые предлагаю поправить

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/index.jsx
> +                        <p className={styles.noMessagesText}>Нет сообщений</p>
Предлагаю убрать лишние отступы, облагородить тем самым элемент сообщения

Чтобы для коротких сообщений не вылетало по ширине, предлагаю отображать в сообщении только first_name \ убрать его за блок [что-то нужно с этим сделать, доверяю твоему взгляду]

<img width="222" alt="изображение" src="https://github.com/user-attachments/assets/23767bd4-0f13-495e-acde-07df051917b2">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/index.jsx
> +                        <p className={styles.noMessagesText}>Нет сообщений</p>
давай для очень маленьких разрешений поправим, чтобы вы вылазило за границы экрана

Стандартно - самая маленькая граница экрана - 320px 
[360px в современном вебе, но давай для бабушек на iphone 4s тоже поддержим]

<img width="452" alt="изображение" src="https://github.com/user-attachments/assets/d69808af-7294-40f0-9cf8-9fe845736086">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/index.jsx
> +                        <p className={styles.noMessagesText}>Нет сообщений</p>
уведомление без текста при попытке создать чела без имени

<img width="461" alt="изображение" src="https://github.com/user-attachments/assets/e782b922-719b-4910-8951-4c7ab5bbeb4f">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/index.jsx
> +                        <p className={styles.noMessagesText}>Нет сообщений</p>
Давай прокачаем доступность:

1. Для этой модалки при ее открытии autofocus выставлять на первое поле ввода
2. Когда модалка открывается, на то, что за ней установить атрибут `inert` [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert]

<img width="373" alt="изображение" src="https://github.com/user-attachments/assets/78948afa-1bc7-4a58-ba28-615641dc5e2d">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/index.jsx
> +                        <p className={styles.noMessagesText}>Нет сообщений</p>
Для менюшки не хватает cursor: pointer, а также предлагаю делать списочек со ссылками 
`<Link to="/profile">` 
[пока должна быть ссылка только на профиль, можно чтобы остальные вели на главную или 404]

<img width="517" alt="изображение" src="https://github.com/user-attachments/assets/0bb00a7f-7590-4e11-91b9-b99566e6e83a">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +    };
классно что задумываешься о клиентской валидации, хотя я о ней [пока] не просил - для других это было допом)

момент из UX, когда ты пишешь в поле ввода, ошибка к нему должна стираться 
[если она показывается]

<img width="452" alt="изображение" src="https://github.com/user-attachments/assets/9bb83ce2-63c1-4aeb-ad99-43eb371807a1">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +    };
Про уменьшение отступов и чтобы не прыгало обговорили в личке

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +    };
После сохранения профиля хотелось бы какой-нибудь алертик увидеть и остаться на странице профиля
Редирект на чатики объясним, но лучше делать по-другому

Пользователю сейчас не очевидно что у него что-то сохранилось, для проверки - ему придется возвратиться в профиль, а это лишнее действие, которое никто не любит

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +                    onChange={(e) => setBio(e.target.value)}
гайд как сделать чуть проще 
[в плане отправки на бэк, обработки ошибок, уменьшения количества кода]

для каждого поля ввода задаешь `name=<название поля на бекенде>`
здесь стоит уточнить, что на бекенде переменные записаны в snake_case, то есть
`first_name`, `last_name`, `bio`, `username`

при отправке на бекенд тебе достаточно закинуть `data` в твой `fetch`, 

данные в data лежат корректные, ошибки сбрасываются при вводе + их удобно будет отображать по возвращении с бекенда 

```
const [errors, setErrors] = useState({});
const [data, setData] = useState({});

const handleChange = (event) => {
    const name = event.target.name;
    const value = event.target.value?.trim();

    setError({ ...error, [name]: null });
    setData({ ...data, [name]: value });
}
```

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +            navigate('/');
вот это пожалуй лишнее [уже отписал про то, что выбрасывать не очень хорошо]

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +                        </span>
Вот такую штуку стоит сделать и в чатике

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +                >
Вот этим элементам стоит быть ссылками `<Link to="/chat/ID">`

Преимущества:
- Не нужен явный navigate
- скринридер сразу видит что это не просто блок, а переход куда-то 
- фокус на элементе отображает ссылку в углу экрана

Недостатки:
- Придется переделать

<img width="668" alt="изображение" src="https://github.com/user-attachments/assets/6c0c186d-2a95-410b-9317-4ff739e5b838">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +            </>
Стоит этот элемент куда-то унести, чтобы подключение было примерно такое 
`<Route path="/" element={<Компонент />} />`

по идее ответственность на PageChatList

<img width="488" alt="изображение" src="https://github.com/user-attachments/assets/f545f751-0a00-42ea-83c0-bc57a16ae981">

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +          </button>
Сделать бы тоже не button, а Link

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/components/Header/index.jsx
>  export default Header;
Я не проконтролировал это раньше поэтому вина на мне

Стоит разбить этот компонент шапки на страничные хедеры
Сейчас присутствуют магические названия `leftElement`, `rightElement`, `centerElement`


Хотелось бы увидеть примерно такую организацию кода

```
components /
    header /
        HeaderChatList.jsx
        HeaderChat.jsx
        HeaderProfile.jsx
        index.jsx - файл внутри которого будет прописано:
                export { HeaderProfile } from "./HeaderProfile.jsx"
                export { HeaderChatList } from "./HeaderChatList.jsx"
                export { HeaderChat } from "./HeaderChat.jsx"
```

2024-10-31 21:00 UTC, sh4rkizz commented on react-chat/src/pages/PageUserProfile/index.jsx
> +                    onChange={(e) => setFirstName(e.target.value)}
Поля нужнаются в .trim()

2024-10-31 21:05 UTC, sh4rkizz commented
Когда обновляешь страницу, будучи в чатике - выбрасывает на главную - не ок

2024-11-03 09:36 UTC, sh4rkizz approved these changes
шикарно! lgtm

2024-11-05 09:20 UTC, merged

2024-11-05 09:20 UTC, martinkomitsky commented
![image](https://github.com/user-attachments/assets/397198bc-991b-46ba-b40c-b9e36a07453c)
уай, это что за машина
12!