ДЗ 7
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #7
Opened 2024-11-14 17:42 UTC by Fellis-a

# Домашнее задание № 7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

[https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/#/login](https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/#/login)

Что было сделано:
* Добавлена форма авторизации и регистрации
* Взаимодействие с бэкендом, написаны запросы, передача сообщений и получение сообщений через Polling
* Добавление чатов (тут пока некорректная работа, но исправлюсь)

2024-11-14 17:51 UTC, Fellis-a commented
https://github.com/user-attachments/assets/7a4fdc14-b358-43e4-9fa2-d1e8b1d51ef9

2024-11-14 22:20 UTC, sh4rkizz requested changes

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +                                <img className={styles.chatAvatar} src={avatarUrl} alt={chatName} />
`alt` это словестное описание того, что на картинке для пользователей скринридеров
chatName в этом поле - недостаточно

```alt={`Аватар пользователя ${chatName}`}``` будет более корректно здесь

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/components/FloatingButton/index.jsx
> +            }
Странно, ведь я не имею чатов с этим пользователем

Подозреваю что виновата эта проверка
`const privateChatExists = existingChats.results.some(chat => chat.is_private);`

Из нее выходит, что может быть только один приватный чат [на странице в целом]

<img width="450" alt="изображение" src="https://github.com/user-attachments/assets/883cdf91-f671-4195-8e52-35bcb2ddc250">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/components/FloatingButton/index.jsx
> +            }
когда отправляешь сообщение, оно сначала появляется без имени отправителя, а потом это имя дорисовывается [поллингом подтягивается сообщение, обновляются его пропсы]

<img width="217" alt="изображение" src="https://github.com/user-attachments/assets/ae9b2172-750e-4a59-958d-087f338bd7dd">

<img width="272" alt="изображение" src="https://github.com/user-attachments/assets/7acd1964-6977-40ad-8a25-c13befffcb73">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageRegister/index.jsx
> +    );
Нужно обработать ошибочки бекенда, 
например дублирующий username

<img width="1225" alt="изображение" src="https://github.com/user-attachments/assets/81b9e06e-ed69-4910-991a-68efa1b625a1">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageRegister/index.jsx
> +    );
Когда регаешься хотелось бы увидеть какую-нибудь модалку
типа красавчик, а теперь войди в свой акк

предлагаю не выдумывать велосипед и сделать по-взрослому
этой штукой будет удобно обратывать ошибки сервера [не код 400, а 403, 404, 429, 5хх]

https://www.npmjs.com/package/react-toastify

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageRegister/index.jsx
> +    );
не забудь здесь подменить ссылку, чтобы редирект вел на дефолтную страницу gh-pages, а не на корень
а то сейчас тык по ссылке выкинет на реальную 404 - https://fellis-a.github.io/

<img width="615" alt="изображение" src="https://github.com/user-attachments/assets/9e04f33b-58c8-4b59-a924-ece676a31218">

<img width="711" alt="изображение" src="https://github.com/user-attachments/assets/e00f26a4-a84a-4e67-9791-906e7ca94e9e">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageRegister/index.jsx
> +    );
Для мобилки мелковаты буквы, при этом в хедере шрифт подобран просто отлично 

<img width="530" alt="изображение" src="https://github.com/user-attachments/assets/cdcc16b1-6837-48cd-99d4-41d64d954971">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/pages/PageRegister/index.jsx
> +    );
нужно добавить `line-height`
часто лучшее решение `line-height = font-size + 4px`, но поскольку здесь шрифт в em, с этим сложнее

<img width="509" alt="изображение" src="https://github.com/user-attachments/assets/6309ca8f-f328-47be-b226-2d01db490420">

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/.env
> +VITE_API_BASE_URL=https://vkedu-fullstack-div2.ru
кажется что нигде не используется, а жаль

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +  const { tokens } = useContext(AuthContext);
токены можно положить в localStorage, чтобы не релогиниться при обновлении страницы

2024-11-14 22:20 UTC, sh4rkizz commented on react-chat/src/api/profile.js
> +};
среди большого количества комментов хочется похвалить за то, как описываешь апишку

с такой организацией кода будет приятно работать в дальнейшем 
[в 9 домашке, когда подключим redux.actions]

2024-11-18 21:50 UTC, sh4rkizz approved these changes
lgtm!

2024-11-19 15:09 UTC, merged

2024-11-19 15:10 UTC, martinkomitsky commented
10