ДЗ 8
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #8
Opened 2024-11-18 13:48 UTC by Fellis-a

# Домашнее задание № 8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Реализована отправка координат пользователя 
* Реализована возможность записи голосового сообщения и добавления файлов, но возникли проблемы с отправкой таких сообщений, дорабатываю

2024-11-24 10:03 UTC, sh4rkizz requested changes

2024-11-24 10:03 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +export default App;
сейчас здесь выводится самое последнее сообщение собеседника, стоит выводить последнее в целом

![изображение](https://github.com/user-attachments/assets/c4d61b72-d022-4b09-af51-0e5c0bd1ccc7)

2024-11-24 10:03 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +export default App;
Давай поправим стиль ссылок, оч плохо видно что там написано
![изображение](https://github.com/user-attachments/assets/9251cdfd-1dcb-43aa-891d-9792da60b7cf)

2024-11-24 10:03 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +export default App;
Давай увеличим кликабельную область кнопки

![изображение](https://github.com/user-attachments/assets/0cf1900e-ad2f-42e1-98c3-7c3f5924eb20)

2024-11-24 10:03 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +export default App;
если перейти к чатику с нулем сообщений [белая страница]
![изображение](https://github.com/user-attachments/assets/ee6c9eeb-9188-41e9-bbf4-e95c74526ded)
![изображение](https://github.com/user-attachments/assets/2d8b3947-eb03-41e6-9329-364ef87b2052)

2024-11-24 10:03 UTC, sh4rkizz commented on react-chat/src/App.jsx
> +export default App;
кажется в шапке чата забыт src за аватаркой

![изображение](https://github.com/user-attachments/assets/2192b7e6-8559-4b01-be62-3c6e9488df8b)

2024-11-25 20:56 UTC, sh4rkizz commented
Кажется еще скролл на списке сообщений куда-то делся)

2024-11-30 08:35 UTC, sh4rkizz submitted a review, later dismissed
lgtm!

2024-11-30 08:36 UTC, sh4rkizz approved these changes
lgtm!

2024-12-06 22:21 UTC, HaseProgram commented
Отлично, 10!

2024-12-06 22:21 UTC, merged