ДЗ 8
Fellis-a/2024-2-VK-EDU-Frontend-A-Fedorova pull request #9
Opened 2024-12-05 12:11 UTC by Fellis-a

# Домашнее задание № 9

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

[https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/](https://fellis-a.github.io/2024-2-VK-EDU-Frontend-A-Fedorova/)

Что было сделано:
* Интеграция Zustand (для юзера, чатов, списка чатов и тд)
* Добавлена возможность удаления аккаунта и чатов
* Добавлена кнопка логаута
* Небольшие доработки для более корректной работы (скролл, возможность отправки изображения через кнопку)

2024-12-06 09:02 UTC, sh4rkizz commented
Давай добавим лоадеры, чтобы не видеть сообщения из другого чата, который был открыт немного ранее

<img width="361" alt="изображение" src="https://github.com/user-attachments/assets/85ee74fc-af7e-478b-bf86-a36902362f50">

2024-12-06 09:05 UTC, sh4rkizz commented
Давай скроем эту штуку, есть вот такой способ

```
width: Xpx;
height: Xpx;

flex: 0 0 Xpx;

/* Fallback image */
background-image: url('<путь до статики, которая встанет, если ссылка сломана>');
background-position: center;
background-size: Xpx;

&::before {
    /* Hide from user, but allow for screen reader */
    position: fixed;
    transform: scale(0);
}
```

<img width="183" alt="изображение" src="https://github.com/user-attachments/assets/c2bbde5e-3bf5-4746-ac20-cb9d01e00a0a">

2024-12-06 09:17 UTC, sh4rkizz requested changes
чини!

2024-12-08 13:05 UTC, sh4rkizz submitted a review, later dismissed
LGTM !!!

2024-12-08 13:05 UTC, sh4rkizz approved these changes
LGTM v2 !!!

2024-12-09 11:08 UTC, merged

2024-12-09 11:08 UTC, martinkomitsky commented
7